### ISSUE TITLE
DB 스키마 정의

### ISSUE THREAD

**Issue by hyejin-1010** [mail-sender/mail_sender_back#1]
- [x] MongoDB 연결
- [x] User Table 정의
- [x] Account Table 정의
- [x] Format Table 정의
- [x] History Table 정의
- [x] Contact Table 정의

**Comment by sangaiostream** [comment]
혜진,,, 부지런하네,,,

**Comment by Kayeon-Do** [comment]
draw.io에 테이블 간단하게 정의해놨는데 추가할 부분 추가해줘! 그리고 contact 부분에 궁금한거 있어서 옆에 따로 적어놓음!

**Comment by hyejin-1010** [comment]
@sangaiostream @Kayeon-Do 

확인해봤을 때 
user.password / contact.email / contact.name / contact.company_name 이 필요할 거 같아서 추가했어.
history 에 attachments (첨부파일 이름(String) List) 필드도 필요할거 같은데, 내가 Row를 늘리는 걸 어떻게 해야할지 몰라서 못했어~

그리고 Contact에 의견 남겼어!

**Comment by Kayeon-Do** [comment]
@sangaiostream @hyejin-1010 넹 history에 attachments col 추가하고 contact 의견 괜찮아서 필드 추가했슴당
